"""Core package for pMOT beam geometry, fields, and atomic-data studies."""

from .atomic_data import (
    choose_polarizability_csv_path,
    DifferentialPolarizabilitySample,
    DifferentialShiftCoefficients,
    RB87CoolingTransition,
    RB87RepumpTransition,
    convert_differential_polarizability_to_mhz_per_intensity,
    default_polarizability_csv_path,
    differential_shift_coefficients_for_wavelength,
    full_range_polarizability_csv_path,
    load_differential_polarizability_csv,
    polarizability_dataframe,
    wavelength_is_in_sample_range,
)
from .beams import GaussianBeam
from .beams import Vec3
from .beams import axis_direction_from_name
from .configuration import MOTBeamConfig
from .configuration import PMOTSimulationConfig
from .configuration import default_simulation_config
from .configuration import describe_configuration
from .configuration import GRAVITY_ACCELERATION_M_PER_S2
from .configuration import notebook_order
from .configuration import project_paths
from .configuration import STANDARD_GRAVITY_M_PER_S2
from .fields import (
    MOTBeam,
    axis_pair_intensity_w_per_m2,
    beam_intensity_w_per_m2,
    beams_for_axis,
    beams_for_family,
    beams_for_polarization,
    build_mot_beams,
    filter_beams,
    sample_axis_pair_intensity_along_line,
    sample_family_intensity_along_line,
    sample_filtered_intensity_along_line,
    sample_intensity_along_line,
    sample_intensity_cloud,
    sample_intensity_cloud_by_polarization,
    sample_intensity_slice,
    sample_intensity_volume,
    total_intensity_w_per_m2,
)
from .forces import (
    AtomState,
    ScatteringSample,
    TrajectoryRecord,
    absorption_kick_velocity_m_per_s,
    beam_scattering_samples,
    doppler_shift_hz,
    effective_detuning_hz,
    emission_kick_velocity_m_per_s,
    recoil_velocity_m_per_s,
    saturation_parameter,
    scattering_rate_per_s,
    simulate_scattering_trajectory,
    total_scattering_rate_per_s,
    transition_for_beam,
    wavevector_magnitude_m_inv,
)
from .trajectories import (
    AnimationSamples,
    TrajectoryDiagnostics,
    animation_samples,
    inward_radial_atom_state,
    trajectory_diagnostics,
    unit_vector_from_angles,
)
from .plotting import (
    plot_apparatus_geometry_3d,
    plot_beam_crossing_zoom,
    plot_intensity_cloud_3d,
    plot_intensity_cloud_3d_by_polarization,
    plot_intensity_lineout,
    plot_polarizability_curves,
    plot_recoil_direction_vectors,
    plot_scalar_field_slice,
    plot_scalar_field_surface,
    plot_velocity_history,
)

__all__ = [
    "DifferentialPolarizabilitySample",
    "DifferentialShiftCoefficients",
    "RB87CoolingTransition",
    "RB87RepumpTransition",
    "choose_polarizability_csv_path",
    "convert_differential_polarizability_to_mhz_per_intensity",
    "default_polarizability_csv_path",
    "differential_shift_coefficients_for_wavelength",
    "full_range_polarizability_csv_path",
    "load_differential_polarizability_csv",
    "polarizability_dataframe",
    "wavelength_is_in_sample_range",
    "GaussianBeam",
    "Vec3",
    "axis_direction_from_name",
    "MOTBeamConfig",
    "PMOTSimulationConfig",
    "default_simulation_config",
    "describe_configuration",
    "GRAVITY_ACCELERATION_M_PER_S2",
    "notebook_order",
    "project_paths",
    "STANDARD_GRAVITY_M_PER_S2",
    "MOTBeam",
    "axis_pair_intensity_w_per_m2",
    "beam_intensity_w_per_m2",
    "beams_for_axis",
    "beams_for_family",
    "beams_for_polarization",
    "build_mot_beams",
    "filter_beams",
    "sample_axis_pair_intensity_along_line",
    "sample_family_intensity_along_line",
    "sample_filtered_intensity_along_line",
    "sample_intensity_along_line",
    "sample_intensity_cloud",
    "sample_intensity_cloud_by_polarization",
    "sample_intensity_slice",
    "sample_intensity_volume",
    "total_intensity_w_per_m2",
    "AtomState",
    "ScatteringSample",
    "TrajectoryRecord",
    "absorption_kick_velocity_m_per_s",
    "beam_scattering_samples",
    "doppler_shift_hz",
    "effective_detuning_hz",
    "emission_kick_velocity_m_per_s",
    "recoil_velocity_m_per_s",
    "saturation_parameter",
    "scattering_rate_per_s",
    "simulate_scattering_trajectory",
    "total_scattering_rate_per_s",
    "transition_for_beam",
    "wavevector_magnitude_m_inv",
    "AnimationSamples",
    "TrajectoryDiagnostics",
    "animation_samples",
    "inward_radial_atom_state",
    "trajectory_diagnostics",
    "unit_vector_from_angles",
    "plot_apparatus_geometry_3d",
    "plot_beam_crossing_zoom",
    "plot_intensity_cloud_3d",
    "plot_intensity_cloud_3d_by_polarization",
    "plot_intensity_lineout",
    "plot_polarizability_curves",
    "plot_recoil_direction_vectors",
    "plot_scalar_field_slice",
    "plot_scalar_field_surface",
    "plot_velocity_history",
]
