"""Shared apparatus primitives for the two-level, multilevel, and pMOT models."""

from .atomic_data import RB87CoolingTransition, RB87RepumpTransition
from .beams import GaussianBeam, Vec3, axis_direction_from_name
from .configuration import (
    AntiHelmholtzCoilConfig,
    AxisDefinition,
    CellGeometry,
    GRAVITY_ACCELERATION_M_PER_S2,
    LensSpec,
    MOTApparatusConfig,
    MOTBeamConfig,
    STANDARD_GRAVITY_M_PER_S2,
    default_mot_apparatus_config,
)
from .fields import (
    MOTBeam,
    axis_pair_intensity_w_per_m2,
    beam_intensity_w_per_m2,
    beams_for_axis,
    beams_for_family,
    beams_for_polarization,
    build_mot_beams,
    filter_beams,
    total_intensity_w_per_m2,
)
from .magnetic_fields import (
    MagneticFieldSample,
    anti_helmholtz_axial_gradient_t_per_m,
    anti_helmholtz_cylindrical_field_t,
    anti_helmholtz_field_t,
    current_for_target_axial_gradient_a,
    default_anti_helmholtz_config,
    field_sample,
    line_sample,
    plane_sample,
    vector_cloud_sample,
)
from .state import AtomState

__all__ = [
    "AntiHelmholtzCoilConfig",
    "AtomState",
    "AxisDefinition",
    "CellGeometry",
    "GRAVITY_ACCELERATION_M_PER_S2",
    "GaussianBeam",
    "LensSpec",
    "MOTApparatusConfig",
    "MOTBeam",
    "MOTBeamConfig",
    "MagneticFieldSample",
    "RB87CoolingTransition",
    "RB87RepumpTransition",
    "STANDARD_GRAVITY_M_PER_S2",
    "Vec3",
    "anti_helmholtz_axial_gradient_t_per_m",
    "anti_helmholtz_cylindrical_field_t",
    "anti_helmholtz_field_t",
    "axis_direction_from_name",
    "axis_pair_intensity_w_per_m2",
    "beam_intensity_w_per_m2",
    "beams_for_axis",
    "beams_for_family",
    "beams_for_polarization",
    "build_mot_beams",
    "current_for_target_axial_gradient_a",
    "default_anti_helmholtz_config",
    "default_mot_apparatus_config",
    "field_sample",
    "filter_beams",
    "line_sample",
    "plane_sample",
    "total_intensity_w_per_m2",
    "vector_cloud_sample",
]
